title: "Nybble Security"
description: "Combinez le consulting IT & Cyber au lieu de les opposer."
url: "https://www.nybble-security.io" # à ajuster si besoin
baseurl: "" # généralement vide pour domaine racine
title_separator: " | "
logo: /assets/img/Nybble-Logo-Horizontal-Blanc_resized.svg
image: /assets/img/hero-banner-seo.webp

# Build
markdown: kramdown
permalink: /:year/:month/:day/:title/


defaults:
- scope:
    path: ""
  values:
    image: /assets/img/hero-banner-seo.webp
- scope:
    path: ""
    type: "posts"
  values:
    layout: post
    seo:
      type: BlogPosting
- scope:
    path: ""
    type: "pages"
  values:
    layout: default


# Plugins autorisés par GitHub Pages
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-target-blank


# Exclusions (non publiées)
exclude: ["README.md", "node_modules", "package.json", "package-lock.json"]


# Langue (utile pour SEO)
lang: fr
