site_name: Nybble Docs
site_url: https://docs.nybble-security.io/
site_description: Nybble documentation website.
site_author: Nybble Engineering Team
nav:
 - Accueil: index.md
 - Nybble Security Analytics:
   - A Propos: nsa/overview.md
   - Release Notes: nsa/release-notes.md 
   - Appliance centrale Filebeat: nsa/filebeat-appliance.md
   - Intégrer un Windows: nsa/windows-onboarding.md
   - Intégrer un Linux: nsa/linux-onboarding.md
   - Intégrer un Firewall: nsa/firewall-onboarding.md
   - Intégrer un équipement réseau: nsa/network-equipments-onboarding.md
 - Nybble Hub:
   - A Propos: nybble-hub/overview.md
   - Release Notes: nybble-hub/release-notes.md
theme: readthedocs
extra_css: [extra.css]
copyright: Copyright &copy; 2022 Nybble Engineering Team for the <a href="https://nybble-security.io">Nybble Company</a>.