site_name: Nybble Docs
site_url: https://docs.nybble-security.io/
site_description: Nybble documentation website.
site_author: Nybble Engineering Team
nav:
 - Home: index.md
 - Nybble Security Analytics:
   - About: nsa/overview.md
   - Filebeat central collector: nsa/filebeat-collector.md
   - Onboard a Windows: nsa/windows-onboarding.md
   - Onboard a Linux: nsa/linux-onboarding.md
   - Onboard a Fortinet device: nsa/fortinet-onboarding.md
   - Onboard a Cisco device: nsa/cisco-onboarding.md
 - Nybble Hub:
   - About: nybble-hub/overview.md
   - Alert Triage: nybble-hub/alert-triage.md
   - Dashboards: nybble-hub/dashboards.md
   - Investigations: nybble-hub/investigations.md
   - Hunt Campaigns (clients): nybble-hub/hunts-clients.md
   - Hunt Campaigns (hunters): nybble-hub/hunts-hunters.md
   - Profile: nybble-hub/profile.md
   - Release Notes: nybble-hub/release-notes.md
theme: readthedocs
extra_css: [extra.css]
copyright: Copyright &copy; 2022 Nybble Engineering Team for the <a href="https://nybble-security.io">Nybble Company</a>.
extra:
  version: "2022.10.18"
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed