site_name: Nybble Docs
site_url: https://docs.nybble-security.io/
site_description: Nybble documentation website.
site_author: Nybble Engineering Team
nav:
 - Home: index.md
 - Nybble Hub:
   - About: nybble-hub/overview.md
   - Authentication: nybble-hub/authentication.md
   - Alert Triage: nybble-hub/alert-triage.md
   - Dashboards: nybble-hub/dashboards.md
   - Investigations: nybble-hub/investigations.md
   #- Hunt Campaigns (clients): nybble-hub/hunts-clients.md
   #- Hunt Campaigns (hunters): nybble-hub/hunts-hunters.md
   - Profile: nybble-hub/profile.md
   - Registration: nybble-hub/register.md
   - Privacy policy: nybble-hub/privacy-policy.md
   - Release Notes: nybble-hub/release-notes.md
   - Terms and Conditions: nybble-hub/terms-and-conditions.md
 - SIEM/EDR Connectors:
   - About: connectors/overview.md
   - Elastic Connector: connectors/elastic-connector.md
   - Sekoia Connector: connectors/sekoia-connector.md
#  - Elastic by Nybble:
#    - About: elastic-by-nybble/overview.md
#    - Filebeat central collector: elastic-by-nybble/filebeat-collector.md
#    - Onboard a Windows: elastic-by-nybble/windows-onboarding.md
#    - Onboard a Linux: elastic-by-nybble/linux-onboarding.md
#    - Onboard a Fortinet device: elastic-by-nybble/fortinet-onboarding.md
#    - Onboard a Cisco device: elastic-by-nybble/cisco-onboarding.md
theme: readthedocs
extra_css: [extra.css]
copyright: Copyright &copy; 2024 Nybble Engineering Team for the <a href="https://nybble-security.io">Nybble Company</a>.
extra:
  version: "2024.06.01"
plugins:
  - search 
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Nybble Docs"
        - locale: fr
          name: Français
          build: true
          site_name: "Documentation Nybble"
          copyright: Copyright &copy; 2024 Nybble Team pour l'entreprise <a href="https://nybble-security.io">Nybble</a>.
          nav_translations:
            Home: "Accueil"
            Nybble Hub: "Nybble Hub"
            About: "A Propos"
            SIEM/EDR Connectors: "Connecteurs SIEM/EDR"
            Authentication: "Authentification"
            Alert Triage: "Qualification d'Alerte"
            Dashboards: "Tableaux de bord"
            Investigations: "Investigations"
            Profile: "Profil"
            Registration: "Inscription"
            Privacy policy: "Politique de Confidentialité"
            Release Notes: "Notes de version"
            Elastic Connector: "Connecteur Elastic"
            Elastic by Nybble: "Elastic By Nybble"
            Sekoia Connector: "Connecteur Sekoia"
            Filebeat central collector: "Filebeat collector (en)"
            Onboard a Windows: "Onboard a Windows (en)"
            Onboard a Linux: "Onboard a Linux (en)"
            Onboard a Fortinet device: "Onboard a Fortinet (en)"
            Onboard a Cisco device: "Onboard a Cisco (en)"
            Terms and Conditions: "Conditions Générales d'Utilisation"
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed