site_name: Nybble Docs
site_url: https://docs.nybble-security.io/
site_description: Nybble documentation website.
site_author: Nybble Engineering Team
nav:
 - Home: index.md
 - Nybble Hub:
   - About: nybble-hub/overview.md
   - Authentication: nybble-hub/authentication.md
   - Alert Triage: nybble-hub/alert-triage.md
   - Dashboards: nybble-hub/dashboards.md
   - Investigations: nybble-hub/investigations.md
   #- Hunt Campaigns (clients): nybble-hub/hunts-clients.md
   #- Hunt Campaigns (hunters): nybble-hub/hunts-hunters.md
   - Profile: nybble-hub/profile.md
   - Registration: nybble-hub/register.md
   - Release Notes: nybble-hub/release-notes.md
 - Bring Your Own SIEM:
   - About: connectors/overview.md
   - Elastic (configuration): connectors/elastic-configuration.md
   - Elastic (connector): connectors/elastic-connector.md
 - Elastic by Nybble:
   - About: elastic-by-nybble/overview.md
   - Filebeat central collector: elastic-by-nybble/filebeat-collector.md
   - Onboard a Windows: elastic-by-nybble/windows-onboarding.md
   - Onboard a Linux: elastic-by-nybble/linux-onboarding.md
   - Onboard a Fortinet device: elastic-by-nybble/fortinet-onboarding.md
   - Onboard a Cisco device: elastic-by-nybble/cisco-onboarding.md
theme: readthedocs
extra_css: [extra.css]
copyright: Copyright &copy; 2023 Nybble Engineering Team for the <a href="https://nybble-security.io">Nybble Company</a>.
extra:
  version: "2023.12.01"
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed